steps:
- name: gcr.io/cloud-builders/docker
  args:
  - pull
  - gcr.io/$PROJECT_ID/scaife-viewer:foo || true
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/scaife-viewer:$COMMIT_SHA
  - "."
images:
- gcr.io/$PROJECT_ID/scaife-viewer:$COMMIT_SHA
options:
  machineType: N1_HIGHCPU_8
