attributions:
  substitutions:
  - match:
      role: "Published original versions of the electronic texts"
      orgs:
      - "Open Greek and Latin"
      names:
      - Gregory Crane
      - Leonard Muellner
      - Bruce Robertson
    data:
      - person:
          name: Gregory Crane
        organization:
          name: Open Greek and Latin
        role: Published original versions of the electronic texts
      - person:
          name: Leonard Muellner
        organization:
          name: Open Greek and Latin
        role: Published original versions of the electronic texts
      - person:
          name: Bruce Robertson
        organization:
          name: Open Greek and Latin
        role: Published original versions of the electronic texts
  - match:
      role: "Published original versions of the electronic texts"
      orgs:
      - "A Digital Corpus for Graeco-Arabic Studies, funded by the Andrew W. Mellon Foundation"
      names:
      - Mark Schiefsky, Harvard University
      - Gregory R. Crane, Universität Leipzig
      - Uwe Vagelpohl, University of Warwick
    data:
      - person:
          name: Mark Schiefsky
        organization:
          name: Harvard University
        role: Published original versions of the electronic texts
      - person:
          name: Gregory R. Crane
        organization:
          name: Universität Leipzig
        role: Published original versions of the electronic texts
      - person:
          name: Uwe Vagelpohl
        organization:
          name: University of Warwick
        role: Published original versions of the electronic texts
  - match:
      role: Editor-in-Chief, Perseus Digital Library
      orgs: []
      names:
      - Gregory Crane
    data:
    - role: Editor-in-Chief, Perseus Digital Library
      person:
        name: Gregory R. Crane
      organization: {}
  - match:
      role: Project Manager (University of Leipzig)
      orgs: []
      names:
      - Matt Munson
    data:
    - role: Project Manager
      person:
        name: Matt Munson
      organization:
        name: University of Leipzig
  - match:
      role: Project Assistant (University of Leipzig)
      orgs: []
      names:
      - Annette Gessner
    data:
    - role: Project Assistant
      person:
        name: "Annette Ge\xDFner"
      organization:
        name: University of Leipzig
  - match:
      role: Lead Developer (University of Leipzig) 2015 - 2017
      orgs: []
      names:
      - "Thibault Cl\xE9rice"
    data:
    - role: Lead Developer
      person:
        name: "Thibault Cl\xE9rice"
      organization:
        name: University of Leipzig
  - match:
      role: Technical Advisor
      orgs: []
      names:
      - Bruce Robertson
    data:
    - role: Technical Advisor
      person:
        name: Bruce Robertson
      organization:
        name: Mount Allison University
  - match:
      role: Lead Developer (University of Leipzig)
      orgs: []
      names:
      - "Thibault Cl\xE9rice"
    data:
    - role: Lead Developer
      person:
        name: "Thibault Cl\xE9rice"
      organization:
        name: University of Leipzig
  - match:
      role: Project Assistant (University of Leipzig)
      orgs: []
      names:
      - "Annette Ge\xDFner"
    data:
    - role: Project Assistant
      person:
        name: "Annette Ge\xDFner"
      organization:
        name: University of Leipzig
  - match:
      role: Project Manager (University of Leipzig), 2013-2014
      orgs: []
      names:
      - Greta Franzini
    data:
    - role: Project Manager
      person:
        name: Greta Franzini
      organization:
        name: University of Leipzig
  - match:
      role: Technical Manager (University of Leipzig), 2013-2015
      orgs: []
      names:
      - Frederik Baumgardt
    data:
    - role: Technical Manager
      person:
        name: Frederik Baumgardt
      organization:
        name: University of Leipzig
  - match:
      role: 'Project Manager (University of Leipzig), 2015

        Project Assistant (University of Leipzig), 2013-2014'
      orgs: []
      names:
      - Simona Stoyanova
    data:
    - role: Project Manager
      person:
        name: Simona Stoyanova
      organization:
        name: University of Leipzig
    - role: Project Assistant
      person:
        name: Simona Stoyanova
      organization:
        name: University of Leipzig
  - match:
      role: Project Assistant (University of Leipzig) 2015 - 2017
      orgs: []
      names:
      - Annette Gessner
    data:
    - role: Project Assistant
      person:
        name: "Annette Ge\xDFner"
      organization:
        name: University of Leipzig
  - match:
      role: Prepared under the supervision of
      orgs: []
      names: []
    data:
    - role: Prepared under the supervision of
      person:
        name: Gregory R. Crane
      organization: {}
  - match:
      role: Keyboarding
      orgs:
      - Perseus Project
      names: []
    data:
    - role: Keyboarding
      person: {}
      organization:
        name: Perseus Digital Library
  - match:
      role: Zoning and proofreading
      orgs:
      - University of Virigina
      names:
      - Rebecca Draughon
    data:
    - role: Digital conversion and editing
      person:
        name: Rebecca Draughon
      organization:
        name: University of Virginia
  - match:
      role: annotation
      orgs: []
      names: []
    data:
    - role: Annotation
      person:
        name: Caroline T. Schroeder
      organization: {}
    - role: Annotation
      person:
        name: Amir Zeldes
      organization: {}
  - match:
      role: source
      orgs: []
      names: []
    data:
    - role: source
      person:
        name: David Brakke
      organization: {}
    - role: source
      person:
        name: Hany Takla
      organization: {}
    - role: source
      person:
        name: J Warren Wells
      organization: {}
  - match:
      role: Librarian for Hellenic Studies and Coordinator for the Classics Collection
        Development
      orgs: []
      names:
      - RHEA LESAGE
    data:
    - role: Librarian for Hellenic Studies and Coordinator for the Classics Collection
        Development
      person:
        name: Rhea Lesage
      organization: {}
  - match:
      role: Proofreading and CTS conversion
      orgs: []
      names:
      - Michael Konieczny
    data:
    - role: Digital Editor
      person:
        name: Michael Konieczny
      organization:
        name: Center for Hellenic Studies
  - match:
      role: Project Manager (University of Leipzig), 2016 - 2018
      orgs: []
      names:
      - Matt Munson
    data:
    - role: Project Manager
      person:
        name: Matt Munson
      organization:
        name: University of Leipzig
  - match:
      role: Project Assistant (University of Leipzig), 2015 - 2017
      orgs: []
      names:
      - Annette Gessner
    data:
    - role: Project Assistant
      person:
        name: Annette Gessner
      organization:
        name: University of Leipzig
  - match:
      role: Lead Developer (University of Leipzig), 2015 - 2017
      orgs: []
      names:
      - "Thibault Cl\xE9rice"
    data:
    - role: Lead Developer
      person:
        name: "Thibault Cl\xE9rice"
      organization:
        name: University of Leipzig
  - match:
      role: Proofreading
      orgs:
      - Mt. Allison University
      names:
      - Kirsten Mason
    data:
    - role: Digital conversion and editing
      person:
        name: Kirsten Mason
      organization:
        name: Mount Allison University
  - match:
      role: Proofreading
      orgs: []
      names:
      - Ann Burns University of Virginia
    data:
    - role: Digital conversion and editing
      person:
        name: Ann Burns
      organization:
        name: University of Virginia
  - match:
      role: Technical Advisor (Mount Allison University)
      orgs: []
      names:
      - Bruce Robertson
    data:
    - role: Technical Advisor
      person:
        name: Bruce Robertson
      organization:
        name: Mount Allison University
  - match:
      role: Proofreading
      orgs:
      - Mt. Allison University
      names:
      - Janan Assaly
    data:
    - role: Digital conversion and editing
      person:
        name: Janan Assaly
      organization:
        name: Mount Allison University
  - match:
      role: Proofreading
      orgs:
      - Center for Hellenic Studies
      names:
      - Janan Assaly
    data:
    - role: Digital conversion and editing
      person:
        name: Janan Assaly
      organization:
        name: Mount Allison University
  - match:
      role: Proofreading and CTS conversion
      orgs: []
      names:
      - Madeline McIntire
      - Michael Konieczny
    data:
    - role: Digital conversion and editing
      person:
        name: Madeline McIntire
      organization:
        name: Mount Allison University
    - role: Digital Editor
      person:
        name: Michael Konieczny
      organization:
        name: Center for Hellenic Studies
  - match:
      role: Proofreading and CTS conversion
      orgs: []
      names:
      - Madeline McIntire
    data:
    - role: Digital conversion and editing
      person:
        name: Madeline McIntire
      organization:
        name: Mount Allison University
  - match:
      role: Proofreading
      orgs: []
      names:
      - Hanhardt Lia
    data:
    - role: Digital conversion and editing
      person:
        name: Lia Hanhardt
      organization:
        name: Center for Hellenic Studies
  - match:
      role: proofreader
      orgs: []
      names:
      - Lia Hanhardt
    data:
    - role: Digital conversion and editing
      person:
        name: Lia Hanhardt
      organization:
        name: Center for Hellenic Studies
  - match:
      role: proofreader
      orgs: []
      names:
      - Hanhardt Lia
    data:
    - role: Digital conversion and editing
      person:
        name: Lia Hanhardt
      organization:
        name: Center for Hellenic Studies
  - match:
      role: Proofreading
      orgs: []
      names:
      - Lia Hanhardt
    data:
    - role: Digital conversion and editing
      person:
        name: Lia Hanhardt
      organization:
        name: Center for Hellenic Studies
  - match:
      role: Proofreading
      orgs:
      - Mt. Allison University
      names:
      - Dawson Fraser
    data:
    - role: Digital conversion and editing
      person:
        name: Dawson Fraser
      organization:
        name: Mount Allison University
  - match:
      role: Proofreading
      orgs:
      - Mt. Allison University
      names:
      - Madeline McIntire
    data:
    - role: Digital conversion and editing
      person:
        name: Madeline McIntire
      organization:
        name: Mount Allison University
  - match:
      role: Proofreading
      orgs: []
      names:
      - Madeline McIntire
    data:
    - role: Digital conversion and editing
      person:
        name: Madeline McIntire
      organization:
        name: Mount Allison University
  - match:
      role: Lead Developer (University of Leipzig) 2015-2017
      orgs: []
      names:
      - "Thibault Cl\xE9rice"
    data:
    - role: Lead Developer
      person:
        name: "Thibault Cl\xE9rice"
      organization:
        name: University of Leipzig
  - match:
      role: Proofreading and CTS conversion
      orgs: []
      names:
      - Jeannie Sellick
    data:
    - role: Digital conversion and editing
      person:
        name: Jeannie Sellick
      organization:
        name: University of Virginia
  - match:
      role: Proofreader
      orgs: []
      names:
      - Ann Burns
    data:
    - role: Digital conversion and editing
      person:
        name: Ann Burns
      organization:
        name: University of Virginia
  - match:
      role: proofreader
      orgs: []
      names:
      - Kirsten Mason
    data:
    - role: Digital conversion and editing
      person:
        name: Kirsten Mason
      organization:
        name: Mount Allison University
  - match:
      role: Lead Developer (University of Leipzig) , 2015- 2017
      orgs: []
      names:
      - "Thibault Cl\xE9rice"
    data:
    - role: Lead Developer
      person:
        name: "Thibault Cl\xE9rice"
      organization:
        name: University of Leipzig
  - match:
      role: Lead Developer (University of Leipzig) , 2015 - 2017
      orgs: []
      names:
      - "Thibault Cl\xE9rice"
    data:
    - role: Lead Developer
      person:
        name: "Thibault Cl\xE9rice"
      organization:
        name: University of Leipzig
  - match:
      role: Proofreading and CTS conversion
      orgs: []
      names:
      - Rebecca Frank
    data:
    - role: Digital conversion and editing
      person:
        name: Rebecca Frank
      organization:
        name: University of Virginia
  promoted:
  - Publisher
  - Additional proofreading and CTS conversion
  - annotation
  - Corrected and encoded the text
  - CTS conversion
  - Keyboarding
  - proofreader
  - Proofreading
  - Proofreading and CTS conversion
  - source
  - Zoning and proofreading
